package uk.co.heywood.categoriser.model;

public enum Category {
    ADDRESS_CHANGE,
    NAME_CHANGE,
    NEW_MEMBER,
    DEATH,
    BENEFICIARY_UPDATE,
    RETIREMENT,
    WITHDRAWAL_REQUEST,
    CONTRIBUTION_UPDATE,
    PENSION_STATEMENT_REQUEST,
    DISABILITY_CLAIM,
    INCOME_CHANGE,
    MARITAL_STATUS_CHANGE,
    EMPLOYMENT_STATUS_CHANGE,
    CONTACT_INFORMATION_UPDATE,
    FAIL
}
